/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ReadMangaImport } from './routes/readManga'
import { Route as MangaDetailsImport } from './routes/mangaDetails'
import { Route as AdvancedSearchImport } from './routes/advancedSearch'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ReadMangaRoute = ReadMangaImport.update({
  path: '/readManga',
  getParentRoute: () => rootRoute,
} as any)

const MangaDetailsRoute = MangaDetailsImport.update({
  path: '/mangaDetails',
  getParentRoute: () => rootRoute,
} as any)

const AdvancedSearchRoute = AdvancedSearchImport.update({
  path: '/advancedSearch',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/advancedSearch': {
      preLoaderRoute: typeof AdvancedSearchImport
      parentRoute: typeof rootRoute
    }
    '/mangaDetails': {
      preLoaderRoute: typeof MangaDetailsImport
      parentRoute: typeof rootRoute
    }
    '/readManga': {
      preLoaderRoute: typeof ReadMangaImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AdvancedSearchRoute,
  MangaDetailsRoute,
  ReadMangaRoute,
])

/* prettier-ignore-end */
